export type Member = {
  id: string;
  name: string;
  email: string;
  phone: string;
  address: string;
  status: 'Active' | 'Inactive';
  joinDate: string; // Will be repurposed for Home Parish for now, can be removed later
  homeParish: string;
  nativeDistrict: string;
  birthday?: string;
  weddingDay?: string;
  family: {
    spouse?: string;
    children?: string[];
  };
  familyName?: string;
  subGroups?: string[];
  avatarUrl: string;
};

export const members: Member[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '555-0101',
    address: '123 Maple St, Anytown, USA',
    status: 'Active',
    joinDate: '2018-03-15',
    homeParish: 'St. Peter\'s Cathedral',
    nativeDistrict: 'Kottayam',
    birthday: '1985-05-20',
    weddingDay: '2010-06-12',
    family: {
      spouse: 'Jane Doe',
      children: ['Jimmy Doe', 'Jenny Doe'],
    },
    familyName: 'Doe Family',
    subGroups: ['Sunday School', 'Choir'],
    avatarUrl: 'https://placehold.co/128x128.png',
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '555-0102',
    address: '456 Oak Ave, Anytown, USA',
    status: 'Active',
    joinDate: '2019-07-22',
    homeParish: 'St. Mary\'s Basilica',
    nativeDistrict: 'Ernakulam',
    birthday: '1990-09-15',
    weddingDay: '2015-10-20',
    family: {
      spouse: 'John Smith',
      children: ['Jake Smith'],
    },
    familyName: 'Smith Family',
    subGroups: ['Youth League'],
    avatarUrl: 'https://placehold.co/128x128.png',
  },
  {
    id: '3',
    name: 'Peter Jones',
    email: 'peter.jones@example.com',
    phone: '555-0103',
    address: '789 Pine Ln, Anytown, USA',
    status: 'Inactive',
    joinDate: '2017-01-30',
    homeParish: 'St. George\'s Church',
    nativeDistrict: 'Thrissur',
    birthday: '1982-01-10',
    family: {},
    familyName: 'Jones Family',
    subGroups: ['Men\'s Fellowship'],
    avatarUrl: 'https://placehold.co/128x128.png',
  },
  {
    id: '4',
    name: 'Mary Johnson',
    email: 'mary.johnson@example.com',
    phone: '555-0104',
    address: '101 Birch Rd, Anytown, USA',
    status: 'Active',
    joinDate: '2020-11-01',
    homeParish: 'St. Peter\'s Cathedral',
    nativeDistrict: 'Pathanamthitta',
    birthday: '1995-03-25',
    family: {
      children: ['Chris Johnson'],
    },
    familyName: 'Johnson Family',
    subGroups: ['Sunday School Teacher'],
    avatarUrl: 'https://placehold.co/128x128.png',
  },
    {
    id: '5',
    name: 'David Williams',
    email: 'david.williams@example.com',
    phone: '555-0105',
    address: '212 Cedar Blvd, Anytown, USA',
    status: 'Active',
    joinDate: '2021-02-14',
    homeParish: 'St. Mary\'s Basilica',
    nativeDistrict: 'Alappuzha',
    birthday: '1978-11-05',
    weddingDay: '2005-02-14',
    family: {
      spouse: 'Susan Williams',
    },
    familyName: 'Williams Family',
    subGroups: ['Pastoral Council'],
    avatarUrl: 'https://placehold.co/128x128.png',
  },
  {
    id: '6',
    name: 'Linda Brown',
    email: 'linda.brown@example.com',
    phone: '555-0106',
    address: '333 Elm St, Anytown, USA',
    status: 'Active',
    joinDate: '2016-06-10',
    homeParish: 'St. George\'s Church',
    nativeDistrict: 'Idukki',
    birthday: '1965-07-30',
    family: {},
    familyName: 'Brown Family',
    avatarUrl: 'https://placehold.co/128x128.png',
  },
  {
    id: '7',
    name: 'James Davis',
    email: 'james.davis@example.com',
    phone: '555-0107',
    address: '444 Spruce Way, Anytown, USA',
    status: 'Active',
    joinDate: '2022-08-19',
    homeParish: 'St. Peter\'s Cathedral',
    nativeDistrict: 'Kollam',
    birthday: '1980-04-01',
    weddingDay: '2008-08-20',
    family: {
      spouse: 'Patricia Davis',
      children: ['Robert Davis', 'Jennifer Davis'],
    },
    familyName: 'Davis Family',
    subGroups: ['Choir', 'Men\'s Fellowship'],
    avatarUrl: 'https://placehold.co/128x128.png',
  },
  {
    id: '8',
    name: 'Barbara Miller',
    email: 'barbara.miller@example.com',
    phone: '555-0108',
    address: '555 Willow Creek, Anytown, USA',
    status: 'Inactive',
    joinDate: '2015-04-12',
    homeParish: 'St. Mary\'s Basilica',
    nativeDistrict: 'Thiruvananthapuram',
    birthday: '1975-02-12',
    weddingDay: '2000-05-15',
    family: {
      spouse: 'Richard Miller',
    },
    familyName: 'Miller Family',
    avatarUrl: 'https://placehold.co/128x128.png',
  },
  {
    id: '9',
    name: 'Michael Wilson',
    email: 'michael.wilson@example.com',
    phone: '555-0109',
    address: '666 Redwood Pkwy, Anytown, USA',
    status: 'Active',
    joinDate: '2023-01-05',
    homeParish: 'St. George\'s Church',
    nativeDistrict: 'Palakkad',
    birthday: '1992-06-18',
    family: {},
    familyName: 'Wilson Family',
    subGroups: ['Youth League'],
    avatarUrl: 'https://placehold.co/128x128.png',
  },
  {
    id: '10',
    name: 'Elizabeth Moore',
    email: 'elizabeth.moore@example.com',
    phone: '555-0110',
    address: '777 Aspen Grove, Anytown, USA',
    status: 'Active',
    joinDate: '2018-09-30',
    homeParish: 'St. Peter\'s Cathedral',
    nativeDistrict: 'Kozhikode',
    birthday: '1988-12-25',
    weddingDay: '2012-01-22',
    family: {
      spouse: 'William Moore',
      children: ['Jessica Moore', 'Daniel Moore'],
    },
    familyName: 'Moore Family',
    subGroups: ['Sunday School Teacher', 'Charity Wing'],
    avatarUrl: 'https://placehold.co/128x128.png',
  },
    {
    id: '11',
    name: 'Charles Taylor',
    email: 'charles.taylor@example.com',
    phone: '555-0111',
    address: '888 Sequoia Trail, Anytown, USA',
    status: 'Active',
    joinDate: '2019-05-25',
    homeParish: 'St. Mary\'s Basilica',
    nativeDistrict: 'Wayanad',
    birthday: '1986-10-10',
    family: {},
    familyName: 'Taylor Family',
    avatarUrl: 'https://placehold.co/128x128.png',
  },
  {
    id: '12',
    name: 'Jessica Anderson',
    email: 'jessica.anderson@example.com',
    phone: '555-0112',
    address: '999 Cypress Ct, Anytown, USA',
    status: 'Active',
    joinDate: '2020-03-17',
    homeParish: 'St. George\'s Church',
    nativeDistrict: 'Kannur',
    birthday: '1991-08-08',
    weddingDay: '2018-02-18',
    family: {
      spouse: 'Thomas Anderson',
      children: ['Sarah Anderson'],
    },
    familyName: 'Anderson Family',
    subGroups: ['Youth League', 'Choir'],
    avatarUrl: 'https://placehold.co/128x128.png',
  }
];
